version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "github_actions"
    - "no-changelog-needed"
- package-ecosystem: "github-actions"
  directory: "/"
  labels:
    - "dependencies"
    - "github_actions"
    - "no-changelog-needed"
  schedule:
    interval: "daily"
  groups:
      actions:
        patterns:
          - "*"
