# Configuration file template for Data analysis of 3D+1D DL3 datasets

# General settings
general:
  log:
    level: info
  outdir: /data/magic/users-ifae/cpriyada/lst/
  n_jobs: 1
  steps: [datasets-3d, fit] #, flux-points, light-curve] datasets-1d # 
  overwrite: true
  stacked_dataset: true

# Target settings
target:
  source_name: PG1553+113
  sky_position: &source_pos {frame: icrs, lon: 238.92934976 deg, lat: 11.19010155 deg}
  use_uniform_position: true
  extended: false
  components:
    name: PG1553+113
    type: SkyModel
    spectral:
      model_name: LogParabola
      type: LogParabolaSpectralModel # For Gammapy Model registry search
      parameters:
      -   name: amplitude
          value: 1e-05
          unit: cm-2 s-1 TeV-1
          error: 1.5e-06
          min: 1e-13
          max: 0.01
          frozen: false
      -   name: reference
          value: 1.5
          unit: GeV
          error: 0.0
          min: 0.001
          max: 100.0
          frozen: true
      -   name: alpha
          value: 1.5
          unit: ''
          error: 0.1
          min: 0.5
          max: 5.0
          frozen: false
      -   name: beta
          value: 0.1
          unit: ''
          error: 0.01
          min: 1e-6
          max: 1.0
          frozen: false
      ebl_abs:
        model_name: dominguez
        type: EBLAbsorptionNormSpectralModel # For Gammapy Model registry search
        redshift: 0.433
        alpha_norm: 1.0
  covariance: None
  from_fermi: false

# Instrument datasets with 3D info
dataset3d:
  type: "3d"
  instruments:
  -   name: Fermi-LAT
      io:
      -   type: lat
          input_dir: /data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/LAT/Analysis1/EBL/LogParabola/
          glob_pattern:
            events: "*MkTime.fits*"
            edisp: "*eDRM.fits*"
            xml_model: "*out.xml"
            exposure: "*BinnedMap.fits*"
            psf: "*psf.fits*"
      -   type: lat-aux
          input_dir: /data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/LAT/diffuse_models/
          glob_pattern:
            diffuse: "gll_iem_v07.fits*"
            iso: "iso_P8R3_SOURCE_V3_*.txt"
      dataset_info:
        name: Fermi-LAT
        key: ["FRONT", "BACK"]
        # map_selection: []
        obs_time:
          format: iso
          intervals: &main_time_range
          -  start: "2021-04-01"
             stop: "2022-05-25"
        background:
          # method: reflected
          # parameters:
          exclusion:
            target_source: true
            regions:
            -   type: CircleAnnulusSkyRegion
                name: None
                position: *source_pos
                parameters:
                  rad_0: 8 deg
                  rad_1: 30 deg
        safe_mask:
          methods: []
          parameters:
            min: 0.1 GeV
            max: 1 TeV
        on_region: *source_pos
          # radius: 0.4 deg # Have to figure how to use this later
        containment_correction: true
        spectral_energy_range: &lat_energy_range
          min: 100 MeV
          max: 1 TeV
          nbins: 2
# - name: HAWC?
#    ... full description ...

# Instrument datasets with 1D info
dataset1d:
  type: "1d"
  instruments:
  -   name: LST-1
      io:
      -   type: lst-1
          input_dir: "/data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/v09x/tailcut84/DL3/real/interp_irf_en_dep/no_tuning/geff_80/teff_80/20220511_dec931/"
          glob_pattern:
            dl3: "202*/dl3*fits"
      dataset_info:
        name: LST-1
        geom:
          selection:
            offset_max: "2.5 deg"
          axes:
            energy: &lst_energy
              min: "10 GeV"
              max: "10 TeV"
              nbins: 5
            energy_true: *lst_energy
        observation:
          # obs_ids: [4333, 4343]
          # obs_file: None
          obs_time:
            format: iso
            intervals: *main_time_range
          required_irfs: ["aeff", "edisp", "rad_max"]
        background:
          method: reflected
          region_finder_method: wobble
          parameters:
            n_off_regions: 1
          exclusion:
            name: None
            position:
              frame: galactic
              lon: 183.604 deg
              lat: -8.708 deg
            region_radius: 0.5 deg
        safe_mask:
          methods: ["custom-mask"]
          parameters:
            min: "10 GeV"
            max: "1 TeV"
            aeff_percent: 10
            bias_percent: 10
            fixed_offset: 0.1 deg
            offset_max: 3 deg
            position: *source_pos
        on_region: *source_pos
        containment_correction: false
        map_selection: [counts, exposure, edisp]
        spectral_energy_range: *lst_energy
#  - name: MAGIC
#      ... full description ...

# Fit parameters
fit_params:
  fit_range: &spectral_energy_range
    min: "100 MeV"
    max: "1 TeV"
  backend: minuit
  optimize_opts: {}
  covariance_opts: {}
  confidence_opts: {}
  store_trace: true

flux_points_params:
  parameters:
    selection_optional: "all"

light_curve_params:
  time_intervals:
    format: "iso"
    intervals:
     -  start: "2021-04-07"
        stop: "2021-04-08"
     -  start: "2021-04-08"
        stop: "2021-04-09"
     -  start: "2021-04-09"
        stop: "2021-04-10"
     -  start: "2021-04-10"
        stop: "2021-04-11"
  energy_edges:
    min: "100 MeV"
    max: "10 TeV"
  parameters:
    selection_optional: "all"

excess_map_params:
  energy_edges:
    min: "100 MeV"
    max: "10 TeV"
  correlation_radius: 0.1 deg
  # parameters:
