# Configuration file template for Data analysis of 3D+1D DL3 datasets

# General settings
general:
  log:
    level: info
  outdir: /data/magic/users-ifae/cpriyada/lst/
  n_jobs: 1
  steps: [datasets-3d, datasets-1d, fit]
  overwrite: true

# Target settings
target:
  source_name: PG1553+113
  sky_position: {frame: icrs, lon: 238.92934976 deg, lat: 11.19010155 deg}
  use_uniform_position: true
  extended: false
  components:
    name: PG1553+113
    type: SkyModel
    spectral:
      model_name: LogParabola
      type: LogParabolaSpectralModel # For Gammapy Model registry search
      parameters:
      -   name: amplitude
          value: 8.2e-06
          unit: cm-2 s-1 TeV-1
          error: 1.5e-06
          min: 0.0
          max: 0.01
          frozen: false
      -   name: reference
          value: 0.01
          unit: TeV
          error: 0.0
          min: 0.001
          max: 100.0
          frozen: true
      -   name: alpha
          value: 1.5
          unit: ''
          error: 0.1
          min: 0.5
          max: 5.0
          frozen: false
      -   name: beta
          value: 0.1
          unit: ''
          error: 0.01
          min: 0.0
          max: 1.0
          frozen: false
      ebl_abs:
        model_name: dominguez
        type: EBLAbsorptionNormSpectralModel # For Gammapy Model registry search
        redshift: 0.433
        alpha_norm: 1.0
  covariance: None
  from_fermi: false

# Instrument datasets with 3D info
dataset3d:
  type: "3d"
  instruments:
  -   name: Fermi-LAT
      io:
      -   type: lat
          input_dir: /data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/LAT/Analysis1/EBL/LogParabola/
          glob_pattern:
            events: "*MkTime.fits*"
            edisp: "*eDRM.fits*"
            xml_model: "*out.xml"
            exposure: "*BinnedMap.fits*"
            psf: "*psf.fits*"
      -   type: lat-aux
          input_dir: /data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/LAT/diffuse_models/
          glob_pattern:
            diffuse: "gll_iem_v07.fits*"
            iso: "iso_P8R3_SOURCE_V3_*.txt"
      dataset_info:
        name: Fermi-LAT
        key: ["FRONT", "BACK"]
        # map_selection: []
        background:
          # method: reflected
          # exclusion: {}
          parameters:
            target_source: true
            regions:
            -   type: CircleAnnulusSkyRegion
                name: None
                position:
                  frame: galactic
                  lon: 120 deg
                  lat: 20 deg
                parameters:
                -   rad_0: 1 deg
                -   rad_1: 2 deg
        safe_mask:
          methods: []
          parameters:
            min: 0.1 GeV
            max: 1 TeV
        on_region:
          frame: "icrs"
          lon: 238.92934976 deg
          lat: 11.19010155 deg
          radius: 0.4 deg
        containment_correction: false
# - name: HAWC?
#    ... full description ...

# Instrument datasets with 1D info
dataset1d:
  type: "1d"
  instruments:
  -   name: LST-1
      io:
      -   type: lst-1
          input_dir: "/data/magic/users-ifae/cpriyada/lst/DL3_all/AGN/PG1553/v09x/tailcut84/DL3/real/interp_irf_en_dep/no_tuning/geff_80/teff_80/20220511_dec931/"
          glob_pattern:
            dl3: "202*/dl3*fits"
      dataset_info:
        name: LST-1
        geom:
          selection:
            offset_max: "2.5 deg"
          axes:
            energy:
              min: "10 GeV"
              max: "10 TeV"
              nbins: 5
            energy_true:
              min: "10 GeV"
              max: "10 TeV"
              nbins: 5
        observation:
          # obs_ids: []
          # obs_file: None
          obs_time:
            start: "2021-01-01"
            stop: "2021-03-30"
          required_irfs: ["aeff", "edisp", "rad_max"]
        background:
          method: reflected
          region_finder_method: wobble
          parameters:
            n_off_regions: 1
          exclusion:
            name: None
            position:
              frame: galactic
              lon: 183.604 deg
              lat: -8.708 deg
            region_radius: 0.5 deg
        safe_mask:
          methods: ["custom-mask"]
          parameters:
            min: "10 GeV"
            max: "10 TeV"
            aeff_percent: 10
            bias_percent: 10
            fixed_offset: 0.1 deg
            offset_max: 3 deg
            position:
              frame: "icrs"
              lon: 238.92934976 deg
              lat: 11.19010155 deg
        on_region:
          frame: "icrs"
          lon: 238.92934976 deg
          lat: 11.19010155 deg
        containment_correction: false
        map_selection: [counts, exposure, edisp]
#  - name: MAGIC
#      ... full description ...

# Fit parameters
fit_params:
  fit_range:
    min: "100 MeV"
    max: "10 TeV"
  backend: minuit
  optimize_opts: {}
  covariance_opts: {}
  confidence_opts: {}
  store_trace: true

flux_points_params:
  energy:
    min: "100 MeV"
    max: "10 TeV"
  parameters:
    selection_optional: "all"

light_curve_params:
  # time_intervals:
  energy_edges:
    min: "100 GeV"
    max: "100 TeV"
  parameters:
    selection_optional: "all"

excess_map_params:
  energy_edges:
    min: "100 MeV"
    max: "10 TeV"
  correlation_radius: 0.1 deg
  # parameters:
