target:
  components:
  -   type: SkyModel
      spectral:
          type: BrokenPowerLaw2SpectralModel
          parameters:
          -   name: amplitude
              value: 1.0e-05
              unit: cm-2 s-1 TeV-1
              error: 1.5e-06
              min: 1.0e-13
              max: 0.01
              frozen: false
          -   name: ebreak
              value: 0.02
              unit: TeV
              error: 0.0
              min: 0.0001
              max: 100.0
              frozen: true
          -   name: index1
              value: 2.0
              unit: ''
              error: 0.1
              min: 0.5
              max: 5.0
              frozen: false
          -   name: index_diff
              value: 1.0
              unit: ''
              error: 0.001
              min: 0.001
              max: 3.0
              frozen: false

