target:
  components:
  -   type: SkyModel
      spectral:
          type: ExpCutoffLogParabolaSpectralModel
          parameters:
          -   name: amplitude
              value: 1.0e-05
              unit: cm-2 s-1 TeV-1
              error: 1.5e-06
              min: 1.0e-13
              max: 0.01
              frozen: false
          -   name: reference
              value: 0.0015
              unit: TeV
              error: 0.0
              min: 0.0001
              max: 100.0
              frozen: true
          -   name: alpha_1
              value: 1.5
              unit: ''
              error: 0.1
              min: 0.5
              max: 5.0
              frozen: false
          -   name: beta
              value: 0.1
              unit: ''
              error: 0.01
              min: 0.01
              max: 1.0
              frozen: false
          -   name: alpha_2
              value: 1
              unit: ''
              error: 0.1
              min: 0.1
              max: 5.0
              frozen: true
          -   name: lambda_ 
              value: 0.05
              unit: TeV-1
              error: 0.01
              min: 1.0e-2
              max: 1.0e6
              frozen: false

