name: Python virtualenv
description: Set up a Python virtual environment with caching
inputs:
  python-version:
    description: The Python version to use
    required: true
  # cache-prefix:
  #   description: Update this to invalidate the cache
  #   required: true
  #   default: v3
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - shell: ${{ runner.shell }}
      run: |
        # Install prerequisites.
        python -m pip install tox

    - shell: ${{ runner.shell }}
      run: |
        # Get the exact Python version to use in the cache key.
        echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: virtualenv-cache
      with:
        path: ${{ runner.path }}
        enableCrossOsArchive: true
        key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}  # ${{ inputs.cache-prefix }}-
        # restore-keys: |
        #   ${{ runner.os }}-pip-

    - if: steps.virtualenv-cache.outputs.cache-hit != 'true'
      shell: ${{ runner.shell }}
      run: |
        # Set up virtual environment without cache hit.
        test -d .venv || virtualenv -p $(which python) --copies --reset-app-data .venv
        echo "${{ runner.venv_activate_command }}"
        python -m pip install -e .[dev]

    - if: steps.virtualenv-cache.outputs.cache-hit == 'true'
      shell: ${{ runner.shell }}
      run: |
        # Set up virtual environment from cache hit.
        echo "${{ runner.venv_activate_command }}"
        python -m pip install --no-deps -e .[dev]

    - shell: ${{ runner.shell }}
      run: |
        # Show environment info.
        echo "${{ runner.venv_activate_command }}"
        echo "✓ Installed $(python --version) virtual environment to $(which python)"
        echo "Packages:"
        python -m pip freeze
