"""
Asgardpy version
"""

try:
    try:
        from ._dev_version import version
    except Exception:
        from ._version import version
except Exception:  # pragma: no cover
    import warnings

    warnings.warn(
        "Could not determine version; this indicates a broken installation."
        " Install from PyPI or from a local git repository."
        " Installing github's autogenerated source release tarballs "
        " does not include version information and should be avoided."
    )
    del warnings
    version = "0.0.0"

__version__ = version

# Save the public version for creating Tags for release
from packaging.version import Version

public_version = Version(__version__).public
__public_version__ = public_version
