name: cffconvert

on:
  push:
    paths:
      - CITATION.cff

jobs:
  validate:
    name: "cffconvert"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v3

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"

      - name: Convert CITATION.cff to Codemeta metadata format
        uses: citation-file-format/cffconvert-github-action@2.0.0
        if: success()
        with:
          args: "--infile ./CITATION.cff --format codemeta --outfile codemeta.json"
