name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  # Change this to invalidate existing cache.
  CACHE_PREFIX: v0
  PYTHONPATH: ./
  PYTEST_ADDOPTS: -v --color=yes

jobs:
  checks:
    name: Python ${{ matrix.python }} - ${{ matrix.task.name }}
    runs-on: [ubuntu-latest-16-cores]
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python: ['3.11']
        task:
          - name: Test
            run: |
              pip install pytest-cov pytest-xdist coverage
              pytest -n auto --dist loadscope --cov --cov-report=xml -m 'test_data or not test_data' asgardpy

        include:
          - python: '3.11'
            task:
              name: Lint
              run: flake8 .

          - python: '3.11'
            task:
              name: Type check
              run: mypy .

          - python: '3.11'
            task:
              name: Build
              run: |
                python setup.py check
                python setup.py bdist_wheel sdist

          - python: '3.11'
            task:
              name: Style
              run: |
                isort --check .
                black --check .

          - python: '3.11'
            task:
              name: Docs
              run: cd docs && make html

          - python: '3.11'
            task:
              name: Spell check
              run: codespell asgardpy

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-venv
        with:
          python-version: ${{ matrix.python }}
          cache-prefix: ${{ env.CACHE_PREFIX }}

      - name: Upload package distribution files
        if: matrix.task.name == 'Build'
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist

      - name: Download Gammapy Datasets
        if: matrix.task.name == 'Test'
        run: |
          python -m pip install tqdm requests
          python -m pip install -e .

          gammapy download datasets

      - name: Download test data
        if: matrix.task.name == 'Test'
        env:
          ASGARDPY_DATA: ${{ secrets.asgardpy_data }}
          GAMMAPY_DATA: /home/runner/work/asgardpy/asgardpy/gammapy-datasets/1.1/
        run: |
          ./download_asgardpy_data.sh

      - name: ${{ matrix.task.name }}
        run: |
          . .venv/bin/activate
          ${{ matrix.task.run }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean up
        if: always()
        run: |
          . .venv/bin/activate
          pip uninstall -y asgardpy

  release:
    name: Release
    runs-on: ubuntu-latest-16-cores
    needs: [checks]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r dev-requirements.txt

      - name: Prepare environment
        run: |
          echo 'RELEASE_VERSION=${GITHUB_REF#refs/tags/v}' >> $GITHUB_ENV
          echo 'TAG=${GITHUB_REF#refs/tags/}' >> $GITHUB_ENV

      - name: Download package distribution files
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist

      - name: Generate release notes
        run: |
          python scripts/release_notes.py > ${{ github.workspace }}-RELEASE_NOTES.md

      - name: Publish package to PyPI
        run: |
          twine upload -u '${{ secrets.PYPI_USERNAME }}' -p '${{ secrets.PYPI_PASSWORD }}' dist/*

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-RELEASE_NOTES.md
          prerelease: ${{ contains(env.TAG, 'rc') }}
          files: |
            dist/*
